
### Get all users
GET http://localhost:9002/api/users

### Get user by ID
GET http://localhost:9002/api/users?id=1

### Get all blogs
GET http://localhost:9002/api/blogs

### Get blog by slug
GET http://localhost:9002/api/blogs/my-first-post

### Get comments for a blog
GET http://localhost:9002/api/blogs/my-first-post/comments

### Create a new blog post
POST http://localhost:9002/api/blogs
Content-Type: application/json

{
  "title": "My New Post",
  "content": "This is the content of my new post.",
  "authorId": "1"
}

### Update a blog post
PUT http://localhost:9002/api/blogs/my-first-post
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content."
}

### Delete a blog post
DELETE http://localhost:9002/api/blogs/my-first-post

### Follow a user
POST http://localhost:9002/api/users/follow
Content-Type: application/json

{
  "userIdToFollow": "2",
  "userId": "1"
}

### Unfollow a user
POST http://localhost:9002/api/users/unfollow
Content-Type: application/json

{
  "userIdToUnfollow": "2",
  "userId": "1"
}

### Create a comment
POST http://localhost:9002/api/blogs/my-first-post/comments
Content-Type: application/json

{
  "content": "This is a great post!"
}
