
### Get all users
GET http://localhost:3000/api/users

### Get user by ID
GET http://localhost:3000/api/users/1

### Get all blogs
GET http://localhost:3000/api/blogs

### Get blog by ID
GET http://localhost:3000/api/blogs/1

### Get blog by slug
GET http://localhost:3000/api/blogs/my-first-post

### Get comments for a blog
GET http://localhost:3000/api/blogs/1/comments

### Create a new blog post
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "My New Post",
  "content": "This is the content of my new post.",
  "authorId": "1"
}

### Update a blog post
PUT http://localhost:3000/api/blogs/1
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content."
}

### Delete a blog post
DELETE http://localhost:3000/api/blogs/1

### Follow a user
POST http://localhost:3000/api/users/follow
Content-Type: application/json

{
  "userIdToFollow": "2",
  "userId": "1"
}

### Unfollow a user
POST http://localhost:3000/api/users/unfollow
Content-Type: application/json

{
  "userIdToUnfollow": "2",
  "userId": "1"
}

### Create a comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "content": "This is a great post!",
  "authorId": "2",
  "postId": "1"
}
